// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

asheep.wad
maps/azuresheep_c03_a3.res
maps/azuresheep_c03_a3_motd.txt
models/cm_v3/bshift/v_9mmar.mdl
models/cm_v3/bshift/v_9mmhandgun.mdl
models/cm_v3/bshift/v_crowbar.mdl
models/cm_v3/bshift/v_grenade.mdl
models/cm_v3/bshift/v_medkit.mdl
models/cm_v3/bshift/v_satchel.mdl
models/cm_v3/bshift/v_satchel_radio.mdl
models/cm_v3/bshift/v_shotgun.mdl
models/mikk/azuresheep/barniel.mdl
models/mikk/azuresheep/barniel01.mdl
models/mikk/azuresheep/barniel02.mdl
models/mikk/azuresheep/barniel03.mdl
models/mikk/azuresheep/barnielt.mdl
models/mikk/azuresheep/global_pt1.txt
models/mikk/azuresheep/mini_osprey.mdl
models/mikk/azuresheep/mini_ospreyt.mdl
models/mikk/skull.mdl
sound/ambience/flareidle.wav
sound/azuresheep_sentences.txt
sound/barniel/_comma.wav
sound/barniel/aimforhead.wav
sound/barniel/badfeeling.wav
sound/barniel/bequiet.wav
sound/barniel/bn_another.wav
sound/barniel/bn_attack1.wav
sound/barniel/bn_becarefull.wav
sound/barniel/bn_bring.wav
sound/barniel/bn_carefull.wav
sound/barniel/bn_close.wav
sound/barniel/bn_die1.wav
sound/barniel/bn_dontdothat.wav
sound/barniel/bn_dontmake.wav
sound/barniel/bn_endline.wav
sound/barniel/bn_firepl.wav
sound/barniel/bn_friends.wav
sound/barniel/bn_gotone.wav
sound/barniel/bn_onelessh.wav
sound/barniel/bn_post.wav
sound/barniel/bn_seethat.wav
sound/barniel/bn_somuch.wav
sound/barniel/bn_tomb.wav
sound/barniel/bn_whatyou.wav
sound/barniel/diegreenthing.wav
sound/barniel/dontagree.wav
sound/barniel/dontknow.wav
sound/barniel/drinktopside.wav
sound/barniel/hearsomething.wav
sound/barniel/hevno.wav
sound/barniel/hi.wav
sound/barniel/hitbad.wav
sound/barniel/humm.wav
sound/barniel/imhit.wav
sound/barniel/movietv.wav
sound/barniel/nosir.wav
sound/barniel/openfire.wav
sound/barniel/rightway.wav
sound/barniel/seelater.wav
sound/barniel/seeya.wav
sound/barniel/slimything.wav
sound/barniel/somethingmoves.wav
sound/barniel/stop1.wav
sound/barniel/teamup1.wav
sound/barniel/teamup2.wav
sound/barniel/thinking.wav
sound/barniel/waitin.wav
sound/barniel/whatsgoingon.wav
sound/barniel/yessir.wav
sound/barniel/youneedmedic.wav
sound/kate/badfelling.wav
sound/kate/bigeye.wav
sound/kate/correctway.wav
sound/kate/cupoftie.wav
sound/kate/freebarney.wav
sound/kate/hevno.wav
sound/kate/hi.wav
sound/kate/hitbad.wav
sound/kate/hitbad2.wav
sound/kate/iamkate.wav
sound/kate/ka_attack1.wav
sound/kate/resquedatlast.wav
sound/kate/seelater.wav
sound/kate/seeyoulater.wav
sound/kate/somethingmove.wav
sound/kate/staypost.wav
sound/kate/teamup1.wav
sound/kate/teamup2.wav
sound/kate/thinking.wav
sound/kate/waithere.wav
sound/kate/waithere2.wav
sound/kate/welcome.wav
sound/kate/whatgoingon.wav
sound/kate/whatgoingon2.wav
sound/kate/yesbarn.wav
sound/kate/youaredead.wav
sound/kate/youwish.wav
