// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

asheep.wad
events/Muzzle_gluongun.txt
maps/azuresheep_c09_a4.res
maps/azuresheep_c09_a4_motd.txt
models/cm_v3/bshift/v_357.mdl
models/cm_v3/bshift/v_saw.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/custom_weapons/gluongun/p_gluongun.mdl
models/custom_weapons/gluongun/v_gluongun.mdl
models/custom_weapons/gluongun/w_clip_gluoncell.mdl
models/custom_weapons/gluongun/w_gluongun.mdl
models/custom_weapons/hlwe/w_clips_all.mdl
models/hlclassic/p_saw.mdl
models/hlclassic/saw_shell.mdl
models/hlclassic/w_saw.mdl
models/mikk/azuresheep/barniel.mdl
models/mikk/azuresheep/barniel01.mdl
models/mikk/azuresheep/barniel02.mdl
models/mikk/azuresheep/barniel03.mdl
models/mikk/azuresheep/barnielt.mdl
models/mikk/azuresheep/global_pt2.txt
models/mikk/azuresheep/p_9mmberetta.mdl
models/mikk/azuresheep/p_m16a2.mdl
models/mikk/azuresheep/sslave.mdl
models/mikk/azuresheep/sslave01.mdl
models/mikk/azuresheep/sslave02.mdl
models/mikk/azuresheep/sslavet.mdl
models/mikk/azuresheep/v_9mmberetta.mdl
models/mikk/azuresheep/v_9mmm41a.mdl
models/mikk/azuresheep/w_9mmberetta.mdl
models/mikk/azuresheep/w_9mmm41a.mdl
scripts/maps/AzureSheep/HLSPClassicMode.as
scripts/maps/AzureSheep/item_healthkit2.as
scripts/maps/AzureSheep/proj_doge.as
scripts/maps/AzureSheep/weapon_9mmberetta.as
scripts/maps/AzureSheep/weapon_9mmm41a.as
scripts/maps/AzureSheep/weapon_blue_rec3.as
scripts/maps/AzureSheep/weapon_hl357.as
scripts/maps/AzureSheep/weapon_ofm249.as
scripts/maps/cubemath/polling_check_players.as
scripts/maps/cubemath/trigger_once_mp.as
scripts/maps/HLSP_azure.as
sound/ambience/lighthum2.wav
sound/azuresheep_sentences.txt
sound/barniel/_comma.wav
sound/barniel/aimforhead.wav
sound/barniel/badfeeling.wav
sound/barniel/bequiet.wav
sound/barniel/bn_another.wav
sound/barniel/bn_attack1.wav
sound/barniel/bn_becarefull.wav
sound/barniel/bn_bring.wav
sound/barniel/bn_carefull.wav
sound/barniel/bn_close.wav
sound/barniel/bn_die1.wav
sound/barniel/bn_dontdothat.wav
sound/barniel/bn_dontmake.wav
sound/barniel/bn_endline.wav
sound/barniel/bn_firepl.wav
sound/barniel/bn_friends.wav
sound/barniel/bn_gotone.wav
sound/barniel/bn_onelessh.wav
sound/barniel/bn_post.wav
sound/barniel/bn_seethat.wav
sound/barniel/bn_somuch.wav
sound/barniel/bn_tomb.wav
sound/barniel/bn_whatyou.wav
sound/barniel/diegreenthing.wav
sound/barniel/dontagree.wav
sound/barniel/dontknow.wav
sound/barniel/drinktopside.wav
sound/barniel/hearsomething.wav
sound/barniel/hevno.wav
sound/barniel/hi.wav
sound/barniel/hitbad.wav
sound/barniel/humm.wav
sound/barniel/imhit.wav
sound/barniel/movietv.wav
sound/barniel/nosir.wav
sound/barniel/openfire.wav
sound/barniel/rightway.wav
sound/barniel/seelater.wav
sound/barniel/seeya.wav
sound/barniel/slimything.wav
sound/barniel/somethingmoves.wav
sound/barniel/stop1.wav
sound/barniel/teamup1.wav
sound/barniel/teamup2.wav
sound/barniel/thinking.wav
sound/barniel/waitin.wav
sound/barniel/whatsgoingon.wav
sound/barniel/yessir.wav
sound/barniel/youneedmedic.wav
sound/cm_v3/saw_reload.wav
sound/cm_v3/saw_reload2.wav
sound/custom_weapons/gluongun/gluon_hitwall.wav
sound/custom_weapons/gluongun/gluon_hitwall2.wav
sound/custom_weapons/gluongun/gluongun_charge.wav
sound/custom_weapons/gluongun/gluongun_fire.wav
sound/custom_weapons/gluongun/gluongun_reload.wav
sound/custom_weapons/gluongun/gluongun_zap.wav
sound/hlclassic/weapons/saw_fire1.wav
sound/hlclassic/weapons/saw_fire2.wav
sound/hlclassic/weapons/saw_fire3.wav
sound/hlclassic/weapons/saw_reload.wav
sound/hlclassic/weapons/saw_reload2.wav
sound/kate/correctway.wav
sound/kate/freebarney.wav
sound/kate/hevno.wav
sound/kate/iamkate.wav
sound/kate/ka_attack1.wav
sound/kate/resquedatlast.wav
sound/kate/seelater.wav
sound/kate/seeyoulater.wav
sound/kate/somethingmove.wav
sound/kate/staypost.wav
sound/kate/waithere.wav
sound/kate/waithere2.wav
sound/kate/welcome.wav
sound/kate/whatgoingon2.wav
sound/kate/yesbarn.wav
sound/kate/youwish.wav
sound/mikk/azuresheep/beretta_fire1.wav
sound/mikk/azuresheep/m41aglauncher.wav
sound/mikk/azuresheep/m41aglauncher2.wav
sound/mikk/azuresheep/m41ahks1.wav
sound/mikk/azuresheep/m41ahks2.wav
sprites/custom_weapons/anim_spr2.spr
sprites/custom_weapons/anim_spr4.spr
sprites/custom_weapons/anim_spr6.spr
sprites/custom_weapons/gluongun.spr
sprites/custom_weapons/gluongun_crosshairs.spr
sprites/custom_weapons/gluongun_ring.spr
sprites/custom_weapons/gluongun_trail.spr
sprites/custom_weapons/weapon_blue_rec3.txt
sprites/gluon_muzzle.spr
sprites/hl_weapons/weapon_hl357.txt
sprites/hl_weapons/weapon_ofm249.txt
sprites/test/320hud1.spr
sprites/test/320hud3.spr
sprites/test/320hudas1.spr
sprites/test/320hudas2.spr
sprites/test/640hud1.spr
sprites/test/640hud4.spr
sprites/test/640hud5.spr
sprites/test/640hudas1.spr
sprites/test/640hudas2.spr
sprites/test/640hudas3.spr
sprites/test/640hudas4.spr
sprites/test/640hudas5.spr
sprites/test/640hudas6.spr
sprites/test/640hudas7.spr
sprites/test/crosshairs.spr
sprites/test/crosshairsas.spr
sprites/test/muzzleflash1.spr
sprites/test/weapon_9mmm41a.txt
sprites/test/weapon_beretta.txt
