// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

asheep.wad
models/mikk/azuresheep/barniel.mdl
models/mikk/azuresheep/barniel01.mdl
models/mikk/azuresheep/barniel02.mdl
models/mikk/azuresheep/barniel03.mdl
models/mikk/azuresheep/barnielt.mdl
models/mikk/azuresheep/gfcar.mdl
models/mikk/azuresheep/p_kmedkit.mdl
models/mikk/azuresheep/p_poolstick.mdl
models/mikk/azuresheep/v_barney9mmar.mdl
models/mikk/azuresheep/v_barney9mmhg.mdl
models/mikk/azuresheep/v_barneygrenade.mdl
models/mikk/azuresheep/v_barneyshotgun.mdl
models/mikk/azuresheep/v_medkit.mdl
models/mikk/azuresheep/v_poolstick.mdl
models/mikk/azuresheep/w_kmedkit.mdl
models/mikk/azuresheep/w_kmedkitt.mdl
models/mikk/azuresheep/w_poolstick.mdl
sound/barney/goon.wav
sound/barniel/_comma.wav
sound/barniel/aimforhead.wav
sound/barniel/badfeeling.wav
sound/barniel/bequiet.wav
sound/barniel/bn_another.wav
sound/barniel/bn_attack1.wav
sound/barniel/bn_becarefull.wav
sound/barniel/bn_bring.wav
sound/barniel/bn_carefull.wav
sound/barniel/bn_close.wav
sound/barniel/bn_die1.wav
sound/barniel/bn_dontdothat.wav
sound/barniel/bn_dontmake.wav
sound/barniel/bn_endline.wav
sound/barniel/bn_firepl.wav
sound/barniel/bn_friends.wav
sound/barniel/bn_gotone.wav
sound/barniel/bn_iwish.wav
sound/barniel/bn_onelessh.wav
sound/barniel/bn_post.wav
sound/barniel/bn_seethat.wav
sound/barniel/bn_somuch.wav
sound/barniel/bn_stepoff.wav
sound/barniel/bn_tomb.wav
sound/barniel/bn_uwish.wav
sound/barniel/bn_whatyou.wav
sound/barniel/diegreenthing.wav
sound/barniel/dontagree.wav
sound/barniel/dontknow.wav
sound/barniel/drinktopside.wav
sound/barniel/hearsomething.wav
sound/barniel/hevno.wav
sound/barniel/hi.wav
sound/barniel/hitbad.wav
sound/barniel/humm.wav
sound/barniel/imhit.wav
sound/barniel/movietv.wav
sound/barniel/nosir.wav
sound/barniel/openfire.wav
sound/barniel/rightway.wav
sound/barniel/seelater.wav
sound/barniel/seeya.wav
sound/barniel/slimything.wav
sound/barniel/somethingmoves.wav
sound/barniel/stop1.wav
sound/barniel/teamup1.wav
sound/barniel/teamup2.wav
sound/barniel/thinking.wav
sound/barniel/waitin.wav
sound/barniel/whatsgoingon.wav
sound/barniel/yessir.wav
sound/barniel/youneedmedic.wav
sound/fvox/health_kate.wav
sound/girl/hctroub.wav
sound/kate/aimforhead.wav
sound/kate/anotherdown.wav
sound/kate/badfelling.wav
sound/kate/becarefull.wav
sound/kate/bequiet.wav
sound/kate/bigeye.wav
sound/kate/bringitone.wav
sound/kate/close.wav
sound/kate/correctway.wav
sound/kate/cupoftie.wav
sound/kate/didntwantthis.wav
sound/kate/didseeshot.wav
sound/kate/dieslimy.wav
sound/kate/dinnerend.wav
sound/kate/dontagree.wav
sound/kate/dontdothat.wav
sound/kate/dontdothis.wav
sound/kate/dontknow.wav
sound/kate/dontwantlive.wav
sound/kate/freebarney.wav
sound/kate/friendslikeyou.wav
sound/kate/gotanother.wav
sound/kate/gotone.wav
sound/kate/hearsomething.wav
sound/kate/hevno.wav
sound/kate/hi.wav
sound/kate/hitbad.wav
sound/kate/hitbad2.wav
sound/kate/hoyes.wav
sound/kate/hummm.wav
sound/kate/iamkate.wav
sound/kate/ka_attack1.wav
sound/kate/muchmore.wav
sound/kate/notatall.wav
sound/kate/oneless.wav
sound/kate/openfire.wav
sound/kate/resquedatlast.wav
sound/kate/seelater.wav
sound/kate/seeyoulater.wav
sound/kate/somethingmove.wav
sound/kate/staypost.wav
sound/kate/stepoff.wav
sound/kate/stop1.wav
sound/kate/teamup1.wav
sound/kate/teamup2.wav
sound/kate/thinking.wav
sound/kate/waithere.wav
sound/kate/waithere2.wav
sound/kate/welcome.wav
sound/kate/whatgoingon.wav
sound/kate/whatgoingon2.wav
sound/kate/whatyoudoing.wav
sound/kate/yesbarn.wav
sound/kate/youaredead.wav
sound/kate/youneedmedic.wav
sound/kate/youwish.wav
sound/scientist/wareh.wav
sound/weapons/kmedkit_sayhealth.wav
