// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/sky_day01_09bk.tga
gfx/env/sky_day01_09dn.tga
gfx/env/sky_day01_09ft.tga
gfx/env/sky_day01_09lf.tga
gfx/env/sky_day01_09rt.tga
gfx/env/sky_day01_09up.tga
hl2ultra.wad
maps/d1_town_04.res
maps/hl2classic.gmr
maps/hl2classic.gsr
models/hl2classic/grigori.mdl
models/hl2classic/headcrab_black.mdl
models/hl2classic/headcrab_fast.mdl
models/hl2classic/v_357.mdl
models/hl2classic/v_9mmar.mdl
models/hl2classic/v_9mmhandgun.mdl
models/hl2classic/v_crowbar.mdl
models/hl2classic/v_shotgun.mdl
models/hl2classic/zombie.mdl
models/hl2classic/zombie01.mdl
props.wad
sound/hl2/monk/attic_apologize.wav
sound/hl2/monk/bucket_almost.wav
sound/hl2/monk/bucket_step.wav
sound/hl2/monk/bucket_thereyouare.wav
sound/hl2/monk/cartrap_iamgrig.wav
sound/hl2/monk/exit_hurry.wav
sound/hl2/monk/exit_salvation.wav
sound/hl2/monk/firetrap_behindyou.wav
sound/hl2/monk/firetrap_vigil.wav
sound/hl2/monk/firetrap_welldone.wav
sound/hl2/monk/madlaugh03.wav
sound/hl2/monk/monk_kill01.wav
sound/hl2/monk/monk_kill02.wav
sound/hl2/monk/monk_kill03.wav
sound/hl2/monk/monk_kill04.wav
sound/hl2/monk/monk_kill05.wav
sound/hl2/monk/monk_kill06.wav
sound/hl2/monk/monk_kill07.wav
sound/hl2/monk/monk_kill08.wav
sound/hl2/monk/monk_kill09.wav
sound/hl2/monk/monk_kill10.wav
sound/hl2/monk/monk_kill11.wav
sound/hl2/monk/shotgun_closer.wav
sound/hl2/monk/shotgun_keepclose.wav
sound/hl2/monk/shotgun_stirreduphell.wav
sound/hl2/monk/wrongside.wav
sound/hl2/monk/yard_greetings.wav
sound/hl2/weapons/357_cock1.wav
sound/hl2/weapons/357_reload1.wav
sound/hl2/weapons/357_reload2.wav
sound/hl2/weapons/357_reload3.wav
sound/hl2/weapons/357_shot2.wav
sound/hl2/weapons/357_spin1.wav
sound/hl2/weapons/dbarrel1.wav
sound/hl2/weapons/dryfire1.wav
sound/hl2/weapons/glauncher1.wav
sound/hl2/weapons/glauncher2.wav
sound/hl2/weapons/hks1.wav
sound/hl2/weapons/hks2.wav
sound/hl2/weapons/hks3.wav
sound/hl2/weapons/pl_gun3.wav
sound/hl2/weapons/reload1.wav
sound/hl2/weapons/reload2.wav
sound/hl2/weapons/reload3.wav
sound/hl2/weapons/sbarrel1.wav
sound/hl2/weapons/scock1.wav
sound/hl2/weapons/shotgun_fire6.wav
sound/hl2/weapons/sshell1.wav
sound/hl2/weapons/sshell2.wav
sound/hl2/weapons/sshell3.wav
sound/hl2classic_sentences.txt
