// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

../media/valve.mp3
eshq.wad
gfx/env/eshq_seaeve_bk.tga
gfx/env/eshq_seaeve_dn.tga
gfx/env/eshq_seaeve_ft.tga
gfx/env/eshq_seaeve_lf.tga
gfx/env/eshq_seaeve_rt.tga
gfx/env/eshq_seaeve_up.tga
hl/weapons/357_reload1.wav
hl/weapons/357_shot1.wav
hl/weapons/357_shot2.wav
maps/eshq21.res
maps/eshq_materials.txt
models/bigspiggot.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/hl/p_357.mdl
models/hl/v_357.mdl
models/hl/w_357.mdl
models/hl/w_357t.mdl
scripts/maps/cubemath/item_healthkit2.as
scripts/maps/cubemath/trigger_mediaplayer.as
scripts/maps/cubemath/trigger_once_mp.as
scripts/maps/hl_weapons/weapon_hl357.as
sound/ambience/b4_disaster.wav
sound/ambience/clank1.wav
sound/ambience/electramb1.wav
sound/ambience/generator1.wav
sound/ambience/generator2.wav
sound/ambience/ring1.wav
sound/ambience/rocketlaunch.wav
sound/ambience/warn10.wav
sound/ambience/warn4.wav
sound/ambience/warn9.wav
sound/eshq/eshq_sentences.txt
sprites/hl_weapons/weapon_hl357.txt
