// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

../media/valve.mp3
eshq.wad
gfx/env/eshq_firnig_bk.tga
gfx/env/eshq_firnig_dn.tga
gfx/env/eshq_firnig_ft.tga
gfx/env/eshq_firnig_lf.tga
gfx/env/eshq_firnig_rt.tga
gfx/env/eshq_firnig_up.tga
hl/weapons/357_reload1.wav
hl/weapons/357_shot1.wav
hl/weapons/357_shot2.wav
maps/eshq24.res
maps/eshq_materials.txt
models/bigspiggot.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/hl/p_357.mdl
models/hl/v_357.mdl
models/hl/w_357.mdl
models/hl/w_357t.mdl
scripts/maps/cubemath/item_healthkit2.as
scripts/maps/cubemath/trigger_mediaplayer.as
scripts/maps/cubemath/trigger_once_mp.as
scripts/maps/hl_weapons/weapon_hl357.as
sound/ambience/electramb2.wav
sound/ambience/GhostCrush.wav
sound/ambience/warn4.wav
sound/eshq/eshq_sentences.txt
sound/plats/gravimover.wav
sound/vox/Ghost01.wav
sound/vox/Ghost02.wav
sound/vox/Ghost03.wav
sound/vox/Ghost04.wav
sound/vox/Ghost05.wav
sound/vox/Ghost06.wav
sprites/hl_weapons/weapon_hl357.txt
