// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

../media/valve.mp3
eshq.wad
gfx/env/eshq_fireve_bk.tga
gfx/env/eshq_fireve_dn.tga
gfx/env/eshq_fireve_ft.tga
gfx/env/eshq_fireve_lf.tga
gfx/env/eshq_fireve_rt.tga
gfx/env/eshq_fireve_up.tga
hl/weapons/357_reload1.wav
hl/weapons/357_shot1.wav
hl/weapons/357_shot2.wav
maps/eshq30.res
maps/eshq_materials.txt
models/bath.mdl
models/bigspiggot.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/hl/p_357.mdl
models/hl/v_357.mdl
models/hl/w_357.mdl
models/hl/w_357t.mdl
models/kitchensink.mdl
models/simplecar.mdl
models/simplejeep.mdl
models/simplepolice.mdl
models/simpletruck.mdl
models/toilet.mdl
scripts/maps/cubemath/item_healthkit2.as
scripts/maps/cubemath/trigger_mediaplayer.as
scripts/maps/cubemath/trigger_once_mp.as
scripts/maps/hl_weapons/weapon_hl357.as
sound/ambience/electramb1.wav
sound/ambience/generator2.wav
sound/ambience/generator3.wav
sound/eshq/eshq_sentences.txt
sprites/hl_weapons/weapon_hl357.txt
