// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

events/Muzzle_gluongun.txt
gfx/detail/detail.tga
halflifebm.wad
maps/HCL_C06_A1_detail.txt
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/cubemath/cursed_e11_blaster/p_cursed_e11_blaster.mdl
models/cubemath/cursed_e11_blaster/v_cursed_e11_blaster.mdl
models/cubemath/cursed_e11_blaster/w_cursed_e11_blaster.mdl
models/custom_weapons/gluongun/p_gluongun.mdl
models/custom_weapons/gluongun/v_gluongun.mdl
models/custom_weapons/gluongun/w_clip_gluoncell.mdl
models/custom_weapons/gluongun/w_gluongun.mdl
models/custom_weapons/hlwe/projectiles.mdl
models/custom_weapons/hlwe/w_clips_all.mdl
models/custom_weapons/redeemer/p_redeemer.mdl
models/custom_weapons/redeemer/v_redeemer.mdl
models/expanded_arsenal/p_autosniper.mdl
models/expanded_arsenal/p_d50.mdl
models/expanded_arsenal/p_flamethrower.mdl
models/expanded_arsenal/v_autosniper.mdl
models/expanded_arsenal/v_d50.mdl
models/expanded_arsenal/v_flamethrower.mdl
models/expanded_arsenal/w_autosniper.mdl
models/expanded_arsenal/w_autosniperclip.mdl
models/expanded_arsenal/w_d50.mdl
models/expanded_arsenal/w_d50ammo.mdl
models/expanded_arsenal/w_flamethrower.mdl
models/hlclassic/p_m40a1.mdl
models/hlclassic/p_saw.mdl
models/hlclassic/pov/v_dualhgun.mdl
models/hlclassic/saw_shell.mdl
models/hlclassic/w_m40a1.mdl
models/hlclassic/w_saw.mdl
models/ins2/ammo/mags.mdl
models/mikk/cp/lambda.mdl
models/mikk/ofhl/alien.mdl
models/mikk/ofhl/alien01.mdl
models/mikk/ofhl/alien02.mdl
models/mikk/ofhl/alient.mdl
models/mikk/ofhl/flashlight_battery.mdl
models/mikk/ofhl/hound.mdl
models/mikk/ofhl/light.mdl
models/mikk/ofhl/lightt.mdl
models/mikk/ofhl/w_battery.mdl
models/mikk/ofhl/wpn/p_usp.mdl
models/mikk/ofhl/wpn/v_357.mdl
models/mikk/ofhl/wpn/v_9mmar.mdl
models/mikk/ofhl/wpn/v_crossbow.mdl
models/mikk/ofhl/wpn/v_crowbar.mdl
models/mikk/ofhl/wpn/v_desert_eagle.mdl
models/mikk/ofhl/wpn/v_displacer.mdl
models/mikk/ofhl/wpn/v_egon.mdl
models/mikk/ofhl/wpn/v_gauss.mdl
models/mikk/ofhl/wpn/v_glock.mdl
models/mikk/ofhl/wpn/v_grenade.mdl
models/mikk/ofhl/wpn/v_knife.mdl
models/mikk/ofhl/wpn/v_m40a1.mdl
models/mikk/ofhl/wpn/v_pipe_wrench.mdl
models/mikk/ofhl/wpn/v_punch.mdl
models/mikk/ofhl/wpn/v_rpg.mdl
models/mikk/ofhl/wpn/v_satchel.mdl
models/mikk/ofhl/wpn/v_satchel_radio.mdl
models/mikk/ofhl/wpn/v_saw.mdl
models/mikk/ofhl/wpn/v_shotgun.mdl
models/mikk/ofhl/wpn/v_spore_launcher.mdl
models/mikk/ofhl/wpn/v_squeak.mdl
models/mikk/ofhl/wpn/v_tripmine.mdl
models/mikk/ofhl/wpn/v_usp.mdl
models/mikk/ofhl/wpn/w_usp.mdl
models/mikk/skull.mdl
sound/cubemath/laser-blaster.wav
sound/custom_weapons/gluongun/gluon_hitwall.wav
sound/custom_weapons/gluongun/gluon_hitwall2.wav
sound/custom_weapons/gluongun/gluongun_charge.wav
sound/custom_weapons/gluongun/gluongun_fire.wav
sound/custom_weapons/gluongun/gluongun_reload.wav
sound/custom_weapons/gluongun/gluongun_zap.wav
sound/custom_weapons/redeemer/redeemer_draw.wav
sound/custom_weapons/redeemer/redeemer_fire.wav
sound/custom_weapons/redeemer/redeemer_reload.wav
sound/custom_weapons/redeemer/redeemer_WH_explode.wav
sound/custom_weapons/redeemer/redeemer_WH_fly.wav
sound/expanded_arsenal/autosniper-1.wav
sound/expanded_arsenal/autosniper_clipin.wav
sound/expanded_arsenal/autosniper_clipout.wav
sound/expanded_arsenal/d50-1.wav
sound/expanded_arsenal/d50-2.wav
sound/expanded_arsenal/d50-3.wav
sound/expanded_arsenal/d50_clipin.wav
sound/expanded_arsenal/d50_clipout.wav
sound/expanded_arsenal/destroyer_clipin.wav
sound/expanded_arsenal/destroyer_clipout.wav
sound/expanded_arsenal/destroyer_draw.wav
sound/expanded_arsenal/dryfire1.wav
sound/expanded_arsenal/fidget_1.wav
sound/expanded_arsenal/fidget_2.wav
sound/expanded_arsenal/fidget_3.wav
sound/expanded_arsenal/fidget_4.wav
sound/expanded_arsenal/items/autosniperinsert1.wav
sound/expanded_arsenal/items/autosniperrelease1.wav
sound/expanded_arsenal/weapon_catch.wav
sound/expanded_arsenal/weapon_draw.wav
sound/expanded_arsenal/weapon_holster.wav
sound/expanded_arsenal/zoom.wav
sound/hlclassic/items/guncock1.wav
sound/hlclassic/weapons/saw_fire1.wav
sound/hlclassic/weapons/saw_fire2.wav
sound/hlclassic/weapons/saw_fire3.wav
sound/hlclassic/weapons/saw_reload.wav
sound/hlclassic/weapons/saw_reload2.wav
sound/hlclassic/weapons/sniper_bolt1.wav
sound/hlclassic/weapons/sniper_bolt2.wav
sound/hlclassic/weapons/sniper_fire.wav
sound/hlclassic/weapons/sniper_reload3.wav
sound/hlclassic/weapons/sniper_reload_first_seq.wav
sound/hlclassic/weapons/sniper_reload_second_seq.wav
sound/hlclassic/weapons/sniper_zoom.wav
sound/ins2/wpn/ammo.ogg
sound/ins2/wpn/empty.ogg
sound/ins2/wpn/fdraw1.ogg
sound/ins2/wpn/fdraw2.ogg
sound/ins2/wpn/fdraw3.ogg
sound/ins2/wpn/fdraw4.ogg
sound/ins2/wpn/fdraw5.ogg
sound/ins2/wpn/fdraw6.ogg
sound/ins2/wpn/ftm2/cap1.ogg
sound/ins2/wpn/ftm2/cap2.ogg
sound/ins2/wpn/ftm2/cap3.ogg
sound/ins2/wpn/ftm2/capon.ogg
sound/ins2/wpn/ftm2/empty.ogg
sound/ins2/wpn/ftm2/end.ogg
sound/ins2/wpn/ftm2/loop.ogg
sound/ins2/wpn/ftm2/start.ogg
sound/ins2/wpn/ftm2/trgoff.ogg
sound/ins2/wpn/ftm2/trgon.ogg
sound/mikk/cp/beamstart4.wav
sound/mikk/cp/beamstart7.wav
sound/mikk/cp/cp.mp3
sound/mikk/cp/particle_suck2.wav
sound/mikk/cp/port_suckout1.wav
sound/mikk/hl2/wpn/usp.wav
sound/mikk/music/hxh_chainbastard.mp3
sound/mikk/ofhl/cbar_hit1.wav
sound/mikk/ofhl/cbar_hit2.wav
sound/mikk/weapons/cbe/cbe_hitbod1.wav
sound/mikk/weapons/cbe/cbe_hitbod2.wav
sound/mikk/weapons/cbe/cbe_hitbod3.wav
sound/mikk/weapons/cbe/cbe_idle1.wav
sound/mikk/weapons/cbe/cbe_off.wav
sound/mikk/weapons/cbe/cbe_on.wav
sprites/custom/640hud1.spr
sprites/custom/640hud2.spr
sprites/custom/640hud4.spr
sprites/custom/640hud5.spr
sprites/custom/weapon_punch.txt
sprites/custom/weapon_the_best.txt
sprites/custom/weapon_usp.txt
sprites/custom/weaponusp1.spr
sprites/custom/weaponusp2.spr
sprites/custom/xhair.spr
sprites/custom_weapons/anim_spr2.spr
sprites/custom_weapons/anim_spr4.spr
sprites/custom_weapons/anim_spr6.spr
sprites/custom_weapons/gluongun.spr
sprites/custom_weapons/gluongun_crosshairs.spr
sprites/custom_weapons/gluongun_ring.spr
sprites/custom_weapons/gluongun_trail.spr
sprites/custom_weapons/redeemer.spr
sprites/custom_weapons/redeemer_crosshairs.spr
sprites/custom_weapons/weapon_blue_rec3.txt
sprites/custom_weapons/weapon_redeemer.txt
sprites/expanded_arsenal/ammo_m2ft.spr
sprites/expanded_arsenal/ammo_new.spr
sprites/expanded_arsenal/autosniper.spr
sprites/expanded_arsenal/autosniper_s.spr
sprites/expanded_arsenal/bipod.spr
sprites/expanded_arsenal/d50.spr
sprites/expanded_arsenal/d50_scope.spr
sprites/expanded_arsenal/sniper_scope.spr
sprites/expanded_arsenal/tfchud07.spr
sprites/expanded_arsenal/weapon_asniper.txt
sprites/expanded_arsenal/weapon_d50.txt
sprites/expanded_arsenal/weapon_flamethrower.txt
sprites/expanded_arsenal/wpn1024.spr
sprites/gluon_muzzle.spr
sprites/hl_weapons/weapon_hl357.txt
sprites/hl_weapons/weapon_hlcrossbow.txt
sprites/hl_weapons/weapon_hlhornetgun.txt
sprites/hl_weapons/weapon_knife.spr
sprites/hl_weapons/weapon_knife.txt
sprites/hl_weapons/weapon_ofm249.txt
sprites/hl_weapons/weapon_ofshockrifle.txt
sprites/hl_weapons/weapon_ofsniperrifle.txt
sprites/ins2/exp/ammo_m2ft.spr
sprites/ins2/fireball1.spr
sprites/ins2/fireball2.spr
sprites/ins2/flame1.spr
sprites/ins2/flame2.spr
sprites/ins2/flame3.spr
sprites/ins2/flame4.spr
sprites/ins2/flame5.spr
sprites/ins2/steam1.spr
sprites/mikk/cp/exit1.spr
sprites/mikk/cp/glow01.spr
sprites/pov/320hud2.spr
sprites/pov/320hudpv1.spr
sprites/pov/640hud7.spr
sprites/pov/640hudpv2.spr
sprites/pov/640hudpv5.spr
sprites/pov/weapon_hornetgundual.txt
