// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

Invasion105.wad
models/metrocop.mdl
models/metrocop01.mdl
models/metrocop02.mdl
models/metrocop03.mdl
models/metrocop04.mdl
models/metrocop05.mdl
models/metrocop06.mdl
models/metrocop07.mdl
sound/ambience/forca01.wav
sound/ambience/guerra01.wav
sound/ambience/vento01.wav
sound/hl2/metrocop/ba_another.wav
sound/hl2/metrocop/ba_bring.wav
sound/hl2/metrocop/ba_buttugly.wav
sound/hl2/metrocop/ba_close.wav
sound/hl2/metrocop/ba_die1.wav
sound/hl2/metrocop/ba_dontmake.wav
sound/hl2/metrocop/ba_dotoyou.wav
sound/hl2/metrocop/ba_endline.wav
sound/hl2/metrocop/ba_firepl.wav
sound/hl2/metrocop/ba_friends.wav
sound/hl2/metrocop/ba_gotone.wav
sound/hl2/metrocop/ba_iwish.wav
sound/hl2/metrocop/ba_pain1.wav
sound/hl2/metrocop/ba_pissme.wav
sound/hl2/metrocop/ba_seethat.wav
sound/hl2/metrocop/ba_somuch.wav
sound/hl2/metrocop/ba_stepoff.wav
sound/hl2/metrocop/ba_tomb.wav
sound/hl2/metrocop/ba_uwish.wav
sound/hl2/metrocop/ba_watchit.wav
sound/hl2/metrocop/ba_whatyou.wav
sound/hl2/metrocop/ba_whoathere.wav
sound/hl2/metrocop/donthurtem.wav
sound/hl2/metrocop/imdead.wav
sound/hl2/metrocop/imhit.wav
sound/hl2/metrocop/leavealone.wav
