// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/cm_v3/op4/v_357.mdl
models/cm_v3/op4/v_9mmAR.mdl
models/cm_v3/op4/v_9mmhandgun.mdl
models/cm_v3/op4/v_knife.mdl
models/cm_v3/op4/v_m40a1.mdl
models/cm_v3/op4/v_saw.mdl
models/cubemath/chars/d0.mdl
models/cubemath/chars/d1.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/hlclassic/p_m40a1.mdl
models/hlclassic/p_saw.mdl
models/hlclassic/saw_shell.mdl
models/hlclassic/w_m40a1.mdl
models/hlclassic/w_saw.mdl
models/mikk/op4/mk_logo.mdl
sound/cm_v2/sniper_bolt1.wav
sound/cm_v2/sniper_bolt2.wav
sound/cm_v2/sniper_reload_first_seq.wav
sound/cm_v2/sniper_reload_second_seq.wav
sound/cm_v3/saw_reload.wav
sound/cm_v3/saw_reload2.wav
sound/hlclassic/weapons/saw_fire1.wav
sound/hlclassic/weapons/saw_fire2.wav
sound/hlclassic/weapons/saw_fire3.wav
sound/hlclassic/weapons/saw_reload.wav
sound/hlclassic/weapons/saw_reload2.wav
sound/hlclassic/weapons/sniper_bolt1.wav
sound/hlclassic/weapons/sniper_bolt2.wav
sound/hlclassic/weapons/sniper_fire.wav
sound/hlclassic/weapons/sniper_reload3.wav
sound/hlclassic/weapons/sniper_reload_first_seq.wav
sound/hlclassic/weapons/sniper_reload_second_seq.wav
sound/hlclassic/weapons/sniper_zoom.wav
sound/mikk/cp/beamstart4.wav
sound/mikk/cp/beamstart7.wav
sound/mikk/cp/particle_suck2.wav
sound/mikk/cp/port_suckout1.wav
sound/mikk/op4/cp.mp3
sprites/antirush/percent.spr
sprites/hl_weapons/weapon_hl9mmhandgun.txt
sprites/hl_weapons/weapon_hlpython.txt
sprites/hl_weapons/weapon_knife.spr
sprites/hl_weapons/weapon_knife.txt
sprites/hl_weapons/weapon_ofm249.txt
sprites/hl_weapons/weapon_ofshockrifle.txt
sprites/hl_weapons/weapon_ofsniperrifle.txt
sprites/mikk/cp/exit1.spr
sprites/mikk/cp/glow01.spr
