// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

maps/opfor_return_demo.res
maps/opfor_return_demo_motd.txt
models/ins2/ammo/mags.mdl
models/ins2/shells/12g_b.mdl
models/ins2/shells/12g_g.mdl
models/ins2/shells/303.mdl
models/ins2/shells/308.mdl
models/ins2/shells/30cal.mdl
models/ins2/shells/45acp.mdl
models/ins2/shells/46x30.mdl
models/ins2/shells/50ae.mdl
models/ins2/shells/545.mdl
models/ins2/shells/556.mdl
models/ins2/shells/556ap.mdl
models/ins2/shells/762.mdl
models/ins2/shells/762t.mdl
models/ins2/shells/762x33.mdl
models/ins2/shells/762x54.mdl
models/ins2/shells/763.mdl
models/ins2/shells/792k.mdl
models/ins2/shells/792x57.mdl
models/ins2/shells/9mm.mdl
models/ins2/shells/9x18.mdl
models/ins2/shells/9x39.mdl
models/ins2/wpn/usp/p_usp.mdl
models/ins2/wpn/usp/v_usp.mdl
models/ins2/wpn/usp/w_usp.mdl
models/mikk/hl2/npc/metrocop.mdl
models/mikk/skull.mdl
models/sc_russian/128_fuse_set02.mdl
models/sc_russian/bjork.mdl
models/sc_russian/bnakettrad5.mdl
models/sc_russian/bus_station.mdl
models/sc_russian/bush39.mdl
models/sc_russian/cagelight00.mdl
models/sc_russian/capacity_cod4_01.mdl
models/sc_russian/cars/78rus_ladasp.mdl
models/sc_russian/cars/78rus_toyota.mdl
models/sc_russian/cc_indistrial_pump_01.mdl
models/sc_russian/cc_shelf.mdl
models/sc_russian/device_szp_001.mdl
models/sc_russian/DGF_flies.mdl
op4return.wad
scripts/maps/hl2/base.as
scripts/maps/hl2/hl777.as
scripts/maps/hl2/main.as
scripts/maps/hl2/weapon_ins2usp.as
sound/ins2/wpn/ammo.ogg
sound/ins2/wpn/bdraw1.ogg
sound/ins2/wpn/bdraw2.ogg
sound/ins2/wpn/bdraw3.ogg
sound/ins2/wpn/empty.ogg
sound/ins2/wpn/fdraw1.ogg
sound/ins2/wpn/fdraw2.ogg
sound/ins2/wpn/fdraw3.ogg
sound/ins2/wpn/fdraw4.ogg
sound/ins2/wpn/fdraw5.ogg
sound/ins2/wpn/fdraw6.ogg
sound/ins2/wpn/gdraw1.ogg
sound/ins2/wpn/gdraw2.ogg
sound/ins2/wpn/gdraw3.ogg
sound/ins2/wpn/gdraw4.ogg
sound/ins2/wpn/hitb1.ogg
sound/ins2/wpn/hitb2.ogg
sound/ins2/wpn/hitb3.ogg
sound/ins2/wpn/hitb4.ogg
sound/ins2/wpn/hitw1.ogg
sound/ins2/wpn/hitw2.ogg
sound/ins2/wpn/hitw3.ogg
sound/ins2/wpn/hitw4.ogg
sound/ins2/wpn/in1.ogg
sound/ins2/wpn/in2.ogg
sound/ins2/wpn/in3.ogg
sound/ins2/wpn/out1.ogg
sound/ins2/wpn/out2.ogg
sound/ins2/wpn/out3.ogg
sound/ins2/wpn/pdraw1.ogg
sound/ins2/wpn/pdraw2.ogg
sound/ins2/wpn/pdraw3.ogg
sound/ins2/wpn/pdraw4.ogg
sound/ins2/wpn/pdraw5.ogg
sound/ins2/wpn/rdraw1.ogg
sound/ins2/wpn/rdraw2.ogg
sound/ins2/wpn/rdraw3.ogg
sound/ins2/wpn/usp/empty.ogg
sound/ins2/wpn/usp/hit.ogg
sound/ins2/wpn/usp/magin.ogg
sound/ins2/wpn/usp/magout.ogg
sound/ins2/wpn/usp/shoot.ogg
sound/ins2/wpn/usp/sldbk.ogg
sound/ins2/wpn/usp/sldrel.ogg
sprites/echoes/spotlight.spr
sprites/ins2/faexplode1.spr
